version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  server:
    build: .
    ports:
      - '3003:3003'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/latex-api
